/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.uv.principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.uv.ps.*;
import org.uv.venta.TablaPieza;

/**
 *
 * @author 2omar
 */
public class Dashboard extends javax.swing.JFrame {

    public Dashboard() {
        initComponents();
        InitStyles();
        SetDate();
        InitContent();
    }

    private void SetDate() {
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", " ;Septiembre",
             "Octubre", "Noviembre", "Diciemrbre"};
        dateText.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);
    }

    private void InitStyles() {
        mensaje.putClientProperty("FlatLaf.styleClass", "h1");
        navText.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        navText.setForeground(Color.white);
        dateText.putClientProperty("FlatLaf.style", "font: 24 $light.font");
        dateText.setForeground(Color.white);
    }

    private void InitContent() {
        ShowJPanel(new Principal());
    }

    public static void ShowJPanel(JPanel p) {
        p.setSize(750, 435);
        p.setLocation(0, 0);

        contentPanel.removeAll();
        contentPanel.add(p, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        btnPrincipal1 = new javax.swing.JButton();
        btnPrincipal5 = new javax.swing.JButton();
        btnPrincipal6 = new javax.swing.JButton();
        btnPrincipal7 = new javax.swing.JButton();
        btnPrincipal8 = new javax.swing.JButton();
        btnPrincipal9 = new javax.swing.JButton();
        btnPrincipal10 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        navText = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(1034, 645));
        fondo.setPreferredSize(new java.awt.Dimension(1034, 645));

        menu.setBackground(new java.awt.Color(13, 71, 161));

        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MEtasoft.jpg"))); // NOI18N

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(13, 71, 161));

        btnPrincipal1.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal1.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio.png"))); // NOI18N
        btnPrincipal1.setText("Principal");
        btnPrincipal1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal1.setBorderPainted(false);
        btnPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal1.setIconTextGap(10);
        btnPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal1ActionPerformed(evt);
            }
        });

        btnPrincipal5.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal5.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extension.png"))); // NOI18N
        btnPrincipal5.setText("Pieza");
        btnPrincipal5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal5.setBorderPainted(false);
        btnPrincipal5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal5.setIconTextGap(10);
        btnPrincipal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal5ActionPerformed(evt);
            }
        });

        btnPrincipal6.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal6.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/processing-car.png"))); // NOI18N
        btnPrincipal6.setText("Material");
        btnPrincipal6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal6.setBorderPainted(false);
        btnPrincipal6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal6.setIconTextGap(10);
        btnPrincipal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal6ActionPerformed(evt);
            }
        });

        btnPrincipal7.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal7.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/product.png"))); // NOI18N
        btnPrincipal7.setText("Producto");
        btnPrincipal7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal7.setBorderPainted(false);
        btnPrincipal7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal7.setIconTextGap(10);
        btnPrincipal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal7ActionPerformed(evt);
            }
        });

        btnPrincipal8.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal8.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proveedor.png"))); // NOI18N
        btnPrincipal8.setText("Proveedor");
        btnPrincipal8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal8.setBorderPainted(false);
        btnPrincipal8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal8.setIconTextGap(10);
        btnPrincipal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal8ActionPerformed(evt);
            }
        });

        btnPrincipal9.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal9.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel-supplier.png"))); // NOI18N
        btnPrincipal9.setText("Proveedor Material");
        btnPrincipal9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal9.setBorderPainted(false);
        btnPrincipal9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal9.setIconTextGap(10);
        btnPrincipal9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal9ActionPerformed(evt);
            }
        });

        btnPrincipal10.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrincipal10.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.png"))); // NOI18N
        btnPrincipal10.setText("Empleado");
        btnPrincipal10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal10.setBorderPainted(false);
        btnPrincipal10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal10.setIconTextGap(10);
        btnPrincipal10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipal10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrincipal10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrincipal7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrincipal5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrincipal6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrincipal8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrincipal9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrincipal10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(25, 118, 210));

        navText.setText("Administración");

        dateText.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText)
                    .addComponent(navText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(navText)
                .addGap(35, 35, 35)
                .addComponent(dateText)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(750, 430));
        contentPanel.setLayout(new java.awt.BorderLayout());

        mensaje.setText("Bienvenido");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal1ActionPerformed
         ShowJPanel(new Principal());
    }//GEN-LAST:event_btnPrincipal1ActionPerformed

    private void btnPrincipal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal5ActionPerformed
        ShowJPanel(new TablaPieza());
    }//GEN-LAST:event_btnPrincipal5ActionPerformed

    private void btnPrincipal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal6ActionPerformed
        
    }//GEN-LAST:event_btnPrincipal6ActionPerformed

    private void btnPrincipal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipal7ActionPerformed

    private void btnPrincipal8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipal8ActionPerformed

    private void btnPrincipal9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipal9ActionPerformed

    private void btnPrincipal10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipal10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipal10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatMaterialLighterIJTheme.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appName;
    private javax.swing.JButton btnPrincipal1;
    private javax.swing.JButton btnPrincipal10;
    private javax.swing.JButton btnPrincipal5;
    private javax.swing.JButton btnPrincipal6;
    private javax.swing.JButton btnPrincipal7;
    private javax.swing.JButton btnPrincipal8;
    private javax.swing.JButton btnPrincipal9;
    private static javax.swing.JPanel contentPanel;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel navText;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
